---
# Global vars
db_name: "{{ project_name}}_dev"
db_user: "{{ project_name }}"
db_pass: "{{ project_name }}"
postgresql_version: 9.5
postgresql_default_auth_method: "md5"
postgresql_databases:
  - name: "{{ db_name  }}"
    owner: "{{ db_user }}"

postgresql_users:
  - name: "{{ db_user | default(project_name) }}"
    pass: "{{ db_pass }}"

postgresql_user_privileges:
  - name: "{{ db_user | default(project_name) }}"
    db: "{{ db_name | default(project_name) }}"
    priv: 'ALL'
    role_attr_flags: 'SUPERUSER'

# Postgres config
postgresql_listen_addresses: "*"

postgresql_pg_hba_default:
  - { type: local, database: all, user: postgres, address: '', method: 'peer', comment: 'database administrative login for Unix domain socket' }
  - { type: local, database: all, user: all, address: '', method: 'md5', comment: '' }

  - { type: local, database: all, user: all, address: '', method: peer, comment: 'local is for Unix domain socket connections only' }
  - { type: host, database: all, user: all, address: 127.0.0.1/32, method: 'md5', comment: 'IP before local connections' }
  - { type: host, database: all, user: all, address: '::1/128', method: 'md5', comment: 'IPv6 local connections' }

